### ISSUE TITLE
Link to the data or mention it is private

### ISSUE THREAD

**Issue by richelbilderbeek** [initc3/forsage#1]
Dear authors of this interesting paper,

Thanks for making the analysis code available! However, for it to run, one also needs the data. 

Could you either provide a link to the data, or -instead- mention the data is private?

I'd love to explore the data a bit!

**Comment by relyt29** [comment]
you should be able to re-collect the data using the ethereum_etl_runner.py script run against a fully synced ethereum archive node such as erigon.

unfortunately it has been a few years, and we no longer retain the data. Additionally the data was quite large so it would not have been feasible to provide a download link for it.
